from django.conf.urls.defaults import *
from django.contrib import admin
from django.conf import settings

admin.autodiscover()

if settings.SERVE_MEDIA:
    urlpatterns = patterns("",
       url(r"", include("staticfiles.urls")),
       )

urlpatterns += patterns('',
    url(r"^contact/", include('legacyredirects.urls')),
    url(r"^about/", include('legacyredirects.urls')),
    url(r"^projects/skills-training-university-based-solar-electricity-courses/", include('legacyredirects.urls')),
    url(r"^projects/development-and-livelihoods-community-charging-stations/", include('legacyredirects.urls')),
    url(r"^projects/education-power-systems-for-secondary-schools/", include('legacyredirects.urls')),
    url(r"^projects/health-electricity-for-rural-health-centres/", include('legacyredirects.urls')),

    url(r'^2010-annual-report', include('legacyblogredirects.urls')),
    url(r'^80016-8551', include('legacyblogredirects.urls')),
    url(r'^africa-rural-connect', include('legacyblogredirects.urls')),
    url(r'^africa-rural-connect-prize', include('legacyblogredirects.urls')),
    url(r'^ausaid-project-equipment-arrives', include('legacyblogredirects.urls')),
    url(r'^community-charging-stationcoming-soon', include('legacyblogredirects.urls')),
    url(r'^efo-a-winner-again-in-the-africa-rural-connect-competition', include('legacyblogredirects.urls')),
    url(r'^efo-and-ewb-kono-clinic', include('legacyblogredirects.urls')),
    url(r'^efo-and-inveneo-to-help-power-microfinance-in-sierra-leone', include('legacyblogredirects.urls')),
    url(r'^efo-helping-in-haiti', include('legacyblogredirects.urls')),
    url(r'^efo-presents-its-education-research-at-african-studies-conference-in-melbourne', include('legacyblogredirects.urls')),
    url(r'^efo-radio-interview', include('legacyblogredirects.urls')),
    url(r'^efo-update-october-2009', include('legacyblogredirects.urls')),
    url(r'^efos-africa-rural-connect-idea', include('legacyblogredirects.urls')),
    url(r'^efos-website-is-released', include('legacyblogredirects.urls')),
    url(r'^energy-for-opportunity-update', include('legacyblogredirects.urls')),
    url(r'^energy-for-opportunityback-in-the-lakka-community', include('legacyblogredirects.urls')),
    url(r'^energy-opportunity-trip-kabala', include('legacyblogredirects.urls')),
    url(r'^fao-flegts-project', include('legacyblogredirects.urls')),
    url(r'^forbes-blog-post-on-energy-for-opportunitys-work', include('legacyblogredirects.urls')),
    url(r'^formal-certification', include('legacyblogredirects.urls')),
    url(r'^funding-updatewebsite-donations', include('legacyblogredirects.urls')),
    url(r'^gbendembu-secondary-school-installation', include('legacyblogredirects.urls')),
    url(r'^go-east-young-man', include('legacyblogredirects.urls')),
    url(r'^icsb-2011-world-conference', include('legacyblogredirects.urls')),
    url(r'^kailahun-government-hospital', include('legacyblogredirects.urls')),
    url(r'^kamabai-community-charging-station-launches', include('legacyblogredirects.urls')),
    url(r'^kamabai-planningthe-not-as-exciting-side-of-work', include('legacyblogredirects.urls')),
    url(r'^kamabai-secondary-school', include('legacyblogredirects.urls')),
    url(r'^kamabai-secondary-school', include('legacyblogredirects.urls')),
    url(r'^kamakwie-and-kamalo-phase-ii', include('legacyblogredirects.urls')),
    url(r'^kamakwie-bound', include('legacyblogredirects.urls')),
    url(r'^kamakwie-ctd', include('legacyblogredirects.urls')),
    url(r'^kamakwie-revisited', include('legacyblogredirects.urls')),
    url(r'^kamakwie-secondary-schoolnow-with-solar-power', include('legacyblogredirects.urls')),
    url(r'^kamakwie-sss-computer-lab', include('legacyblogredirects.urls')),
    url(r'^koinadugu-district-planning-trip', include('legacyblogredirects.urls')),
    url(r'^koinadugu-district-water-pumping-and-irrigation', include('legacyblogredirects.urls')),
    url(r'^koindu-town-kailahun', include('legacyblogredirects.urls')),
    url(r'^lighting-africa-2010', include('legacyblogredirects.urls')),
    url(r'^makeni-installations-are-complete', include('legacyblogredirects.urls')),
    url(r'^new-efo-logo', include('legacyblogredirects.urls')),
    url(r'^new-york-times-article-impact-of-small-scale-solar', include('legacyblogredirects.urls')),
    url(r'^outamba-kilimi-national-park-and-tambakka-chiefdom', include('legacyblogredirects.urls')),
    url(r'^outback-power-and-bp-solar-donations', include('legacyblogredirects.urls')),
    url(r'^princeton-intern-kamakwie-computer-training', include('legacyblogredirects.urls')),
    url(r'^project-2-kamakwie-orphanage', include('legacyblogredirects.urls')),
    url(r'^san-francisco-learns-about-efo', include('legacyblogredirects.urls')),
    url(r'^sierra-leone-first-renewable-energy-forum', include('legacyblogredirects.urls')),
    url(r'^sierra-leone-solar-power-documentary', include('legacyblogredirects.urls')),
    url(r'^solar-installation-video', include('legacyblogredirects.urls')),
    url(r'^solar-installed-community-led-tourism-resort-river-2', include('legacyblogredirects.urls')),
    url(r'^solar-power-sierra-leone', include('legacyblogredirects.urls')),
    url(r'^solar-system-st-martins-orphanage-port-loko-proving-be-great-success', include('legacyblogredirects.urls')),
    url(r'^solar-water-pumping-course', include('legacyblogredirects.urls')),
    url(r'^st-martins-orphanage', include('legacyblogredirects.urls')),
    url(r'^st-martins-orphanage-port-loko', include('legacyblogredirects.urls')),
    url(r'^update-and-new-project', include('legacyblogredirects.urls')),
    url(r'^updates-from-kamabai', include('legacyblogredirects.urls')),
    url(r'^updates-from-the-field', include('legacyblogredirects.urls')),
    url(r'^west-african-solar-revolution', include('legacyblogredirects.urls')),

    url(r'^blog/comments/', include('django.contrib.comments.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r"^search/", include("search.urls")),
    url(r'^admin/filebrowser/', include('filebrowser.urls')),
    url(r'^', include('cms.urls')),
    url(r"^programmes/", include("programmes.urls")),
    url(r"^projects/", include("projects.urls")),
    url(r"^contact-us/", include("contact.urls")),
    url(r"^members/", include("profiles.urls")),
    url(r"^account/logout/$", 
        "pinax_local.apps.account.views.logout",
        {
            "template_name": "account/logout.html",
            "next_page": "/"
        }, name="logout"),
    url(r'^blog/', include('zinnia.urls')),
)

if settings.DEBUG:
    urlpatterns = patterns('',
        (r'^' + settings.MEDIA_URL.lstrip('/'), include('appmedia.urls')),
    ) + urlpatterns

